[package]
name = "sharded-vec-writer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Write parts of a Vec from different threads"
repository = "https://github.com/davidlattimore/sharded-vec-writer"

[dependencies]
